name: Vercel PR Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEXT_PUBLIC_COSMIC_BUCKET_SLUG: ${{ secrets.NEXT_PUBLIC_COSMIC_BUCKET_SLUG }}
  NEXT_PUBLIC_COSMIC_READ_KEY: ${{ secrets.NEXT_PUBLIC_COSMIC_READ_KEY}}
  NEXT_PUBLIC_COSMIC_WRITE_KEY: ${{ secrets.NEXT_PUBLIC_COSMIC_WRITE_KEY}}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
on:
  pull_request:
jobs:
  pr-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy \
            --token="$VERCEL_TOKEN" \
            --build-env NEXT_PUBLIC_COSMIC_BUCKET_SLUG="$NEXT_PUBLIC_COSMIC_BUCKET_SLUG" \
            --build-env NEXT_PUBLIC_COSMIC_READ_KEY="$NEXT_PUBLIC_COSMIC_READ_KEY" \
            --build-env NEXT_PUBLIC_COSMIC_WRITE_KEY="$NEXT_PUBLIC_COSMIC_WRITE_KEY" \
            --env NEXT_PUBLIC_COSMIC_BUCKET_SLUG="$NEXT_PUBLIC_COSMIC_BUCKET_SLUG" \
            --env NEXT_PUBLIC_COSMIC_READ_KEY="$NEXT_PUBLIC_COSMIC_READ_KEY" \
            --env NEXT_PUBLIC_COSMIC_WRITE_KEY="$NEXT_PUBLIC_COSMIC_WRITE_KEY"
